backend:
  name: git-gateway
  branch: main

media_folder: "images/catalog"
public_folder: "/images/catalog"

collections:
  - name: "products"
    label: "Products"
    label_singular: "Product"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price (zł)", name: "price", widget: "number", value_type: "int" }
      - { label: "Category", name: "category", widget: "select", options: ["tradycyjne", "owocowe", "musowe", "bezowe", "dziecięce"] }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "img", widget: "image" }
      - { label: "Product ID", name: "id", widget: "number" }

